### ISSUE TITLE
Loading libcups from environment does not work

### ISSUE THREAD

**Issue by JochenLutz** [hugomarquez/ffi-cups#1]
We don't have `cups-devel` installed on our production system and therefore don't have `libcups.so`, but only `libcups.so.2`.

Therefore using `ffi-cups` fails with `LoadError: Could not open library 'cups': cups: cannot open shared object file: No such file or directory. Could not open library 'libcups.so': libcups.so: cannot open shared object file: No such file or directory`.

Giving the full filename via `ENV['CUPS_LIB']` (as implemented in `ffi-cups.rb`) does not work, because `ffi-cups/ffi/array.rb`, `ffi-cups/ffi/cups.rb` and `ffi-cups/ffi/http.rb` don't honor the value from ENV, but always use `ffi_lib('cups')`.

**Comment by hugomarquez** [comment]
Please test it out on your environment and let me know how it goes, for now I'm closing this issue
