### ISSUE TITLE
Unknown method Cups.cupsLastErrorString()

### ISSUE THREAD

**Issue by JochenLutz** [hugomarquez/ffi-cups#2]
In `lib/ffi-cups/printer.rb:60`: `last_error = Cups.cupsLastErrorString()`.

I guess that should be `FFI::Cups.cupsLastErrorString()`.

**Comment by hugomarquez** [comment]
Hi @JochenLutz , thanks for using ffi-cups, yes I agree there is a syntax issue there, I'll fix it along with #1 and bump it to version 0.3.0 on rubygems so you can test it out!

Thanks for reaching out!

**Comment by hugomarquez** [comment]
Fixed on release v0.3.0, closing this issue now
